json.id product.id
json.name product.name
json.price product.price
json.description product.description
json.is_discounted product.is_discounted?
json.tax product.tax
json.total product.total
json.stock_status product.stock_status
json.supplier_name product.supplier.name
json.image_url product.images
json.categories product.categories
